name: Org-Team-Activity

on:
  schedule:
    - cron: "0 0 * * *" # sekali sehari (00:00 UTC / 07:00 WIB)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Team Activity
        run: node scripts/org-stats.mjs
        env:
          # kalau gagal "Resource not accessible by integration",
          # ganti dengan ${{ secrets.SUMMARY_GITHUB_TOKEN }} (PAT)
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ORG: Kafeinarts
          UTC_OFFSET: 7

      - name: Commit hasil
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add asset/org-stats.svg
          git diff --staged --quiet || (git commit -m "chore: update team activity" && git push)
